config/routes.rb
Rails.application.routes.draw do
  root to: "main#index" 
  # GET /about 
  get 'about', to: "about#index"

  # password routes
  get "password", to: "passwords#edit", as: :edit_password 
  patch "password", to: "passwords#update"

  # GET /sign_up
  get 'sign_up', to: "registrations#new"
  post 'sign_up', to: "registrations#create"
  delete 'logout', to: "sessions#destroy"

  # sign_in form
  get 'sign_in', to: "sessions#new"
  # sign_in submission
  post 'sign_in', to: "sessions#create"

  # password reset
  get "password_reset", to: "password_resets#new"
  post "password_reset", to: "password_reset#create"
  get "password_reset_edit", to: "password_resets#new"
  patch "password_reset_edit", to: "password_reset#update"

  resources :blogs 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :content, presence: true 
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user 
end

app/models/user.rb
# email:string, password_digest:string
# w/ has_secure_password...password:string virtual, password_confirmation:string virtual
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/, message: "must be a valid email address" }
    #validates :email, format : {with: URI::MailTo::Email_REGEXP}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            # look up user by id
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    # GET - show all blogs
    def index 
        @blogs = Blog.all 
    end

    # GET - request page with form to create a blog
    def new 
        @blog = Blog.new
    end

    # POST - create blog
    def create 
        @blog = Blog.new(blog_params)

        if @blog.save
            flash[:notice] = "Blog successfully saved."
        else
            flash[:notice] = "There was an error when creating a blog."
            render :new, status: :unprocessable_entity 
        end
    end

    # GET - edit blog
    def edit 
        @blog = Blog.find(params[:id])
    end

    def update 
        @blog = Blog.find(params[:id])

        if @blog.update(blog_params)
            redirect_to blog_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private
    def blog_params
        params.required(:blog).permit(:title, :content)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index 
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new 
    end

    def create 
        @user = User.find_by(email: params[:email])

        if @user.present?
            # send email
            PasswordMailer.with(user: @user).reset.deliver_now
        end
        redirect_to root_path, notice: "If an account with that email was found, we will send a link to reset your password."
    end

    def edit 
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired. Please try again."
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(passowrd_params)
        else
            render :edit
        end
    end

    private 

    def passowrd_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    
    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password Updated!"
        else
            render :edit
        end 
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmations)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    # create a new user
    def new
        @user = User.new 
    end

    def create 
        @user = User.new(user_params)
        # this signs in user...runs validation and inserts to database. 
        if @user.save
            # setting a 'session' cookie to keep track of user being signed in
            # session gets encrypted to get stored as a  cookie
            # add user id into the session as database id
            session[:user_id] = @user.id 
            redirect_to root_path, notice: "Successfully created account"
        else
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmations)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create 
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id 
            redirect_to root_path, notice: "Logged in Successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new 
        end
    end

    def destroy 
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/blogs/_form.html.erb
<%= form_with model: @blog do |form| %>
    <div class="card" style="width: 20rem">
        <% if @blog.errors.any? %>
            <% @blog.errors.full_messages.each do |message| %>
            <div>
                <% message %>
            </div>
            <% end %>
        <% end %>
        <div >
            <%= form.label :title %>
            <%= form.text_field :title %>
        </div>

        <div class="card-text">
            <%= form.label :content %>
            <%= form.text_field :content %>
        </div>
        
        <%= form.submit %>
    </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit: <%= @blog.title %></h1>

<%= render "form" %>

app/views/blogs/index.html.erb
<h1>Thoughts</h1>
<% @blogs.each do |blog| %>
<div class="card card-body" style="width: 18rem;">
    <div class="card-title"> 
    <h2 ><%= blog.title %></h2>
    </div>
    <p class="card-text">Content: <%= blog.content %></p>
    <div>
        <%= link_to "edit", edit_blog_path(blog) %>

        <%= button_to "Edit", edit_blog_path(blog), class: "btn btn-pirmary", method: :get %>
    </div>
</div>
<% end %> 

app/views/blogs/new.html.erb
<h1>Create a Blog</h1>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1 class="title">Welcome to Flourish</h1>
    <% image_tag 'Flour.png', alt: "Flourish" %>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
      <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_message.each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %>

     <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-controll", placeholder: "password" %>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-controll", placeholder: "password" %>
    </div>
    
    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Your Password</h1>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-controll", placeholder: "mac@gmail.com" %>
    </div>
    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Blogs", blogs_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create New Blog", new_blog_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-item">
          <%= link_to Current.user.email, edit_password_path, class: "nav_link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-outline-secondary" %>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_up_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    
    </div>
  </div>
</nav>